# Generated by Django 4.0.4 on 2022-05-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='summary',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
