# Generated by Django 4.0.3 on 2022-04-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_blogmodel_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
