# Generated by Django 4.0.3 on 2022-04-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogmodel_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
