# Generated by Django 4.0.3 on 2022-04-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_blogmodel_managers_blogmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogmodel',
            managers=[
            ],
        ),
    ]
