# Generated by Django 4.0.4 on 2022-04-19 20:10

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('home', '0010_remove_blogmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='all_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
