# Generated by Django 4.0.4 on 2022-04-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_blogmodel_tags_blogmodel_all_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='home.tag'),
        ),
    ]
