# Generated by Django 4.0.4 on 2022-04-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_newsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
